### ISSUE TITLE
After training, odd regularly sized repeating square outlines leave artifacts on images

### ISSUE THREAD

**Issue by kyrieb-ekat** [DDMAL/Rodan#1209] opened 2024-09-17 16:11 UTC
After training images will have, to varying degrees, odd repeating square outlines on images. I've now managed to replicate this consistently with a model on a variety of simple black and white text images. I have attached the models and images below. The artifacted lines- which may have a better term than what I'm using, so I apologize in advance for any confusion- appear to frequently remove a strip from one layer and place it into another. The squares show up most clearly and consistently on larger images. 

The text images I used only had two layers: annotated layer (Layer 1) and background. The gaps from the 'squares' disappear in layer 1 and show up in background. They show poorly here, so I've copied one of the sample images into a text file with a white background to give a clear demonstrations of what's happening- the others replicate this to varying degrees. 

![Abecedarian bold on white bg](https://github.com/user-attachments/assets/799a9ba7-318d-411d-a0d8-27115b309c75)

Image names and their sizes produced by Rodan (original files at end):

AB - 571x521
BC - 543x364
CD - 571x347
DE - 551x379
Alphabet Clear BG - 7810x5176
Alphabet White BG - 611x786
Lorem Ipsum - 513x672
Abecedarian Bold - 587x777

Note: the lines  are very hard to see on a black background, so they can also be viewed here, along with the model files (https://drive.google.com/drive/folders/1PI1uvjzxI775Lcc6a7FGODhueopdDGAQ?usp=sharing) if you don't want to change the GitHub black background to see them. 

![L1 DE - Letter test 4 - DE](https://github.com/user-attachments/assets/27d1100e-e999-4f71-9924-3bfda61d61cc)
![L0 DE - Letter test 4 - DE](https://github.com/user-attachments/assets/841d2696-f02a-4cc7-b2c8-14c322753e2f)
![L1 CD - Letter test 3 - CD](https://github.com/user-attachments/assets/daaf6a7a-41a4-456e-96bf-55683b643f54)
![L0 CD - Letter test 3 - CD](https://github.com/user-attachments/assets/3b5d763a-b49d-44d5-9136-2f73a8768a1d)
![L1 BC - Letter test 2 - BC](https://github.com/user-attachments/assets/79419df6-8008-4f43-a03e-b3b10668d234)
![L0 BC - Letter test 2 - BC](https://github.com/user-attachments/assets/93905145-8970-4a60-a9ff-f313bad10a6e)
![L1 AB - RODAN letter test](https://github.com/user-attachments/assets/921633f1-96f4-400d-810c-ff18e407bfee)
![L0 AB - RODAN letter test](https://github.com/user-attachments/assets/611d5d69-78bb-4ba7-b0b5-35975a2f7b93)
![L1 Alphabet Clear BG - Fast Pixelwise Analysis of Music Document, Classifying - Layer 1](https://github.com/user-attachments/assets/aae25528-aabd-4668-8e94-e8ec602e4c9b)
![L0 Alphabet Clear BG - Fast Pixelwise Analysis of Music Document, Classifying - Background Layer](https://github.com/user-attachments/assets/7c473a1b-0b08-422e-84dd-774bf9fef9ca)
![L1 Alphabet - Fast Pixelwise Analysis of Music Document, Classifying - Layer 1](https://github.com/user-attachments/assets/cb87949c-3bf9-4b5c-8f25-f539dbcea56e)
![L0 Alphabet - Fast Pixelwise Analysis of Music Document, Classifying - Background Layer](https://github.com/user-attachments/assets/b7ddaf14-75cb-4f8f-b323-d99a1aecee5f)
![L1 Lorum Ipsum - Fast Pixelwise Analysis of Music Document, Classifying - Layer 1](https://github.com/user-attachments/assets/ecd0b74b-a149-4fcf-add4-3965c8266700)
![L0 Lorem Ipsum - Fast Pixelwise Analysis of Music Document, Classifying - Background Layer](https://github.com/user-attachments/assets/7aa5da04-0ce6-4389-a565-e8797f991b5d)
![L1 Abecedarian Bold - Fast Pixelwise Analysis of Music Document, Classifying - Layer 1](https://github.com/user-attachments/assets/1224c010-893f-4d50-9e63-a2a1e81faa4c)
![L0 Abecedarian Bold - Fast Pixelwise Analysis of Music Document, Classifying - Background Layer](https://github.com/user-attachments/assets/11cd5616-7ac6-450a-b9d1-3a0e8fcf3d77)

Original Images uploaded to classifying job: 

![RODAN letter test](https://github.com/user-attachments/assets/01f66aa2-94ed-4814-bcf7-a025e3359de3)
![Screenshot 2024-09-16 at 9 29 51 AM](https://github.com/user-attachments/assets/e1abb906-29b6-49fe-a045-14d80f0ee496)
![Screenshot 2024-09-16 at 9 30 04 AM](https://github.com/user-attachments/assets/90a4b323-8558-4f83-9b1c-7d1ff12391d8)
![Screenshot 2024-09-16 at 9 30 14 AM](https://github.com/user-attachments/assets/8937025d-4240-4841-ac6a-d2a1929831cf)
![Screenshot 2024-09-16 at 10 33 26 AM](https://github.com/user-attachments/assets/ace6fe71-be3c-44b7-8f82-a6855963eac3)
![Screenshot 2024-09-16 at 11 06 32 AM](https://github.com/user-attachments/assets/ba3efa66-f500-4a96-aaf6-db74175e1efc)
![Screenshot 2024-09-16 at 11 14 37 AM](https://github.com/user-attachments/assets/74c90893-4eef-431d-b26a-7c14a85f558c)
![Screenshot 2024-09-16 at 10 59 47 AM](https://github.com/user-attachments/assets/3af4ca76-893d-43d8-a708-8bc8f48a9261)
![Alphabet-Letters-Black-Clip-Art](https://github.com/user-attachments/assets/9d769ba1-f484-4a16-8379-931958369b26)

Workflow is below. All images are separated using the Fast Pixelwise Classifier. Images/line artifact gaps might be easier to see if downloaded and opened over a white background. Background removal job not utilised
![Screenshot 2024-09-16 at 11 26 18 AM](https://github.com/user-attachments/assets/24a32085-0249-4308-ae29-996a0487251a)
![Screenshot 2024-09-16 at 11 26 07 AM](https://github.com/user-attachments/assets/68d1eccf-18ee-403e-966d-691b07915218)

@JoyfulGen if you have any other models which consistently produce the squares, please feel free to drop them- or if you run into.think of any other circumstances which provoke them.

**Comment by kyrieb-ekat** [comment] 2024-09-17 16:49
For a larger demonstration of this squares phenomena, and perhaps also the layer combining/separating issue (#1207), see the below image. Note that the white dots appearing on the manuscript cover above the parchment aren't present in the manuscript image, and appear to be bleed through from the squares present on layer 3.  


![Screenshot 2024-09-17 at 12 48 59 PM](https://github.com/user-attachments/assets/fd530234-b805-4a2e-925a-3ff39f5e1cfd)
![Screenshot 2024-09-17 at 12 48 54 PM](https://github.com/user-attachments/assets/deb689e4-072c-495a-b556-752c971b076c)

**Comment by fjcastellanos** [comment] 2024-09-24 11:06
Hello, I have located the bug in the code, and it should be fixed now. The problem is in inference (not in training). I have updated the repository with the correction. After several tests, I haven’t encountered the problem again. I hope this fix has definitively resolved the issue. Thank you very much for reporting the error.

**Comment by fjcastellanos** [comment] 2024-09-30 17:53
Hi, of course, the fix is in this [commit](https://github.com/DDMAL/Paco_classifier/commit/f73d0d3f5345620d4034547320959e84d16d5a67), in the Paco_classifier repo.

**Closed** 2024-11-01 18:52 UTC
Labels: bug, priority: Medium
