### ISSUE TITLE
jobs with multiple output files do not have proper naming with batch inputs

### ISSUE THREAD

**Issue by kyrieb-ekat** [DDMAL/Rodan#1190] opened 2024-07-15 13:52 UTC
When you're processing a lot of images through the classifying job, the layers it separates and outputs won't be renamed "job name - Layer X" etc, as it does when you process single images. This makes sifting through and renaming relevant layers somewhat problematic if you need to search and use specific layers for another job, etc. Examples attached below (Image 1, multiple images with layers separated, image 2 a single image with layers separated and successfully renamed). 

![Screenshot 2024-07-15 at 9 51 21 AM](https://github.com/user-attachments/assets/cdcfbf06-540f-4da1-939f-055d1c2f4b00)
![Screenshot 2024-07-15 at 9 51 50 AM](https://github.com/user-attachments/assets/0f596ef2-e82d-4ca5-9167-ea6c4277549b)

**Comment by homework36** [comment] 2024-07-16 17:20
What do you think should be the expected naming practice for this?

**Comment by kyrieb-ekat** [comment] 2024-07-16 18:18
Probably would just need to do what it does for the single upload (the BaRa3 example), where it just puts the file name at the front of "Fast Pixelwise... - Layer X", unless you think abridging it might be more helpful/useful.

**Comment by homework36** [comment] 2024-07-16 18:20
Okay. I'll check and fix it.

**Comment by homework36** [comment] 2024-09-09 17:09
Some notes for myself:
File paths and naming are handled by Django `upload_to` which should work fine and we do not do anything else manually in terms of naming or renaming output files.
Looks like when there're multiple outputs for one inputs, `outputs[opt_name]["is_list"]` is still False (`opt_name` is the job name according to `logger` msg). I'm not sure but it seems to me that it should be a list when there're multiple outputs. There're a few lines in `RodanTaskType` [`__init__`](https://github.com/DDMAL/Rodan/blob/4c7f761bcedc25848ade133b569bf016aa090eb5/rodan-main/code/rodan/jobs/base.py#L163C21-L169C63) that seems to do something related but we never actually get into the else block of the `if attrs.get("_abstract") is True` statement.

**Comment by homework36** [comment] 2024-09-13 16:20
I believe naming of output files is handled here
https://github.com/DDMAL/Rodan/blob/e5f620dcfac55721a858ddbec81d85f73bc22dbe/rodan-main/code/rodan/jobs/core.py#L247

However, I cannot print out file names etc using `logger.info` for this with the following setting 
```
import logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("rodan")
```

**Comment by homework36** [comment] 2024-09-14 00:24
Just took another look at `package_results`. 
The two packaging modes work as follows:
Mode 0:
```
tmp_dir/
  Job1 - OutputPortA/
    Resource1.txt
    Resource2.txt
  Job2 - OutputPortB/
    ResourceList1/
      00.jpg
      01.jpg
```
Mode 1:
```
tmp_dir/
  Resource1/
    Job1 - OutputPortA.txt
  Resource2/
    Job2 - OutputPortB.txt
  ResourceList1/
    Job2 - OutputPortB.list/
      00.jpg
      01.jpg
```
However, none of the directory structures are reflected on the resources page. We need to check (1) is this is really used by Rodan and (2) how is this show up with Rodan client.

**Comment by homework36** [comment] 2024-09-20 15:32
I was able to find out how to modify names for output resources. However, I discovered that our resource names are managed poorly. Sometimes the output resource is named after the job name, and sometimes it uses the same name as the input resource specified by the user. I thought about this and realize that it is indeed a tricky thing to do, because we can easily run into the following scenarios:
1. single input, single output
2. single input, multiple outputs
3. multiple inputs, single output
4. multiple inputs, multiple outputs
And with batch feeding inputs, it can be further complicated.
While I had a quick discussion with @kyrieb-ekat what we should do, I found #1001 which mentions the job `Labeler`. I tested with a simple case and it turns out very useful in this case.
There was a followup issue #1127 for `Labeler` but I wasn't able to reproduce this on my local server. When I ran my tests, it works as expected.
Maybe we should work on this and/or make a job like `Renamer` in a similar fashion?

**Comment by homework36** [comment] 2024-11-01 18:47
See #1221. 

> Users should consider the file formatting themselves. For example, "custom prefix - " will lead to "custom prefix - old name" while "custom prefix" will become"custom prefixold name".

**Comment by JoyfulGen** [comment] 2024-11-14 22:29
This issue was a duplicate, so I closed it: https://github.com/DDMAL/Rodan/issues/729

**Comment by homework36** [comment] 2024-11-15 20:23
This is fixed (or achieved in Resource Distributor)

**Closed by homework36** 2024-11-15 20:23 UTC
Labels: Priority: HIGH, Type: FIX, Rodan Client, help-wanted
