### ISSUE TITLE
PNG, Non-Interactive Classifier and Text Alignment jobs behaving inconsistently

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#779] opened 2022-09-27 15:08 UTC
When running a complete OMR workflow, the PNG or NIC jobs sometimes get stuck (the status says "Processing" forever) and the text alignement job sometimes fails. To try to narrow down the situation, I went through the following process:

1. I ran a complete workflow with 244v - Result: the workflow was succesful
2. I ran a complete workflow with 244r - Result: the first PNG job got stuck
3. I ran a PNG job alone with 244r - Result: the job was sucessful
4. I logged out of rodan, logged back in and tried 244r again - Result: no job got stuck, but text alignment failed
5. I ran text alignment alone with the background layer of 244r that failed in the previous workflow - Result: the job failed
6. I ran a complete workflow with 242r - Result: two PNG jobs got stuck (I don't know which) and text alignment failed
7. I ran text alignment alone with the background layer of 242r that failed in the previous workflow - Result: the job failed

So for now, I can't reproduce the jobs getting stuck, but I can reproduce text alignement failing; if I use the same resources that failed the first time, the job will fail again. Here are some relevant resources:

[242v.txt](https://github.com/DDMAL/Rodan/files/9657681/242v.txt)
[244r.txt](https://github.com/DDMAL/Rodan/files/9657682/244r.txt)
[244v.txt](https://github.com/DDMAL/Rodan/files/9657683/244v.txt)
[Einsiedeln__Stiftsbibliothek__Codex_611_242r.jpg.zip](https://github.com/DDMAL/Rodan/files/9657686/Einsiedeln__Stiftsbibliothek__Codex_611_242r.jpg.zip)
[Einsiedeln__Stiftsbibliothek__Codex_611_244r.jpg.zip](https://github.com/DDMAL/Rodan/files/9657690/Einsiedeln__Stiftsbibliothek__Codex_611_244r.jpg.zip)
[Einsiedeln__Stiftsbibliothek__Codex_611_244v.jpg.zip](https://github.com/DDMAL/Rodan/files/9657700/Einsiedeln__Stiftsbibliothek__Codex_611_244v.jpg.zip)

The background layers were too big for this issue, so I put them here: https://drive.google.com/drive/folders/1Wh-jB_xok87vtK3rKmkmI2Dd58Lqatpo?usp=sharing

Let me know if you need anything else!

**Comment by JoyfulGen** [comment] 2022-09-28 13:23
Just one more bit of information: I tried combining the background layer of 244r (which failed twice) with the text file of 244v (which was successful). It failed again, which rules out a problem with the text file. The background file is the problem.

**Comment by softcat477** [comment] 2022-09-28 14:24
Are you using this workflow?
<img width="1202" alt="isThisTheCompleteOMRWorkflow" src="https://user-images.githubusercontent.com/25975988/192804880-c44a69c2-0064-413e-a25e-ab7e2c55febf.png">

**Comment by sabrina0822** [comment] 2022-09-29 14:49
Sorry about that production is back up!

**Comment by timothydereuse** [comment] 2022-10-07 18:44
During the image preprocessing... process, folio 244r turns into this: 
![image](https://user-images.githubusercontent.com/28409383/194627590-d09e2e4e-ed44-47ed-8131-8ef4002c859c.png)

(we SHOULD be seeing the text of the folio in white on a black background. instead, it's getting some kind of blocky inverted version of the staves?)

Anyway, this wreaks havoc with all kinds of thing later in the process. Going to figure out why these files are behaving like this.

**Comment by timothydereuse** [comment] 2022-10-07 20:23
I tested this PR with all the images you posted, Gen, and they all seem to work for me. I hope this is the root cause. No idea about the inconsistent behavior of the PNG jobs, though...

**Comment by JoyfulGen** [comment] 2022-10-09 11:37
@timothydereuse the PNG jobs seem to have stopped acting out. Don't know what that was about, but the PNG jobs all work quickly now! Is your fix for text alignment in production, or not yet?

**Comment by timothydereuse** [comment] 2022-10-12 17:16
Not yet, it will be in staging soon! I'll let you know when it's ready to test.

**Comment by timothydereuse** [comment] 2022-10-14 21:41
Okay, now it's for SURE in staging. I tested it and it worked. I'll close this issue if we don't find anything else that breaks in the text-alignment job.

**Comment by timothydereuse** [comment] 2022-10-27 17:06
Closing this since text alignment is working again, and the PNG issues seem more related to other problems that Wanyi has been working on (e.g. https://github.com/DDMAL/Rodan/issues/797).

**Closed by timothydereuse** 2022-10-27 17:06 UTC
Labels: Priority: HIGH, Text Alignment, bug
